In [3]:
import requests
from bs4 import BeautifulSoup

In [ ]:
# 뉴스 데이터 수집 함수 정의
def get_news_data(keyword, total_news=50):
    news_list = []
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    }
    for start in range(1, total_news + 1, 10):
        url = f"https://search.naver.com/search.naver?where=news&ie=utf8&sm=nws_hty&query={keyword}&start={start}"
        res = requests.get(url, headers=headers)
        soup = BeautifulSoup(res.text, "html.parser")
        articles = soup.select('div[data-sds-comp="Profile"]')
        for article in articles:
            if len(news_list) >= total_news:
                break
            article_box = article.parent
            title_element = article_box.select_one('a[data-heatmap-target=".tit"]')
            title = title_element.get_text(strip=True) if title_element else "제목없음"
            press_element = article_box.select_one(
                "span.sds-comps-profile-info-title-text"
            )
            press = (
                press_element.get_text(strip=True) if press_element else "언론사없음"
            )
            summary_element = article_box.select_one(
                'span[class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-3 sds-comps-text-type-body1"]'
            )
            summary = summary_element.get_text(strip=True) if summary_element else None
            news_list.append({"title": title, "press": press, "summary": summary})
    return news_list

In [ ]:
# 수집한 데이터 확인용 코드
def print_get_news_data(keyword):
    result = get_news_data(keyword)

    for idx, news in enumerate(result, 1):
        print(f"[{idx}] {news['title']} ({news['press']})")
        print(f" - {news['summary']}\n")

In [6]:
print_get_news_data(keyword="코스피")

[1] 코스피, 외국인 복귀에 2.7% 상승 5,370대 마감…코스닥도 올라(종합) (연합뉴스)
 - 환율 급락 속 외국인 12일만에 '사자'…삼성전자·하이닉스 급등 알테오젠, 에코프로 제치고 코스닥 시총 1위…삼천당제약 나흘만 반등코스피가 3일 외국인이 12거래일 만에 '사자'로 돌아선 가운데 상승해 5,370대를 회복했다. 이날코스피는 전장보다 143.25포인트(2.74%) 오른 5,377.30에 장을 마쳤다....

[2] 코스피, 외국인 매수에 5,370대 회복…코스닥도 올라 (부산일보)
 - None

[3] 외국인, 12일 만에 귀환…코스피, 2%대 상승 마감(종합) (뉴시스)
 - 미국 도널드 트럼프 대통령의 이란 전쟁 관련 강경 발언의 여파로 급락했던코스피가 호르무즈 해협 통항에 대한 기대감이 퍼지면서 상승 마감했다. 3일코스피는 외국인과 기관의 매수세에 힘입어 전 거래일(5234.05)보다 143.25포인트(2.74%) 오른 5377.30에 마감했다. 지수는 전날 미국 도널드 트럼프...

[4] 외국인의 귀환…코스피, 2%대 상승 마감 (채널A)
 - None

[5] 안철수 “코스피비명지르는데 대통령·여당은 셀카 파티…전쟁 위기 맞... (문화일보)
 - 의원이 “코스피사이드카 터질 때, 이 대통령과 민주당은 국회에서 환호, 박수, 셀카 파티를 했다”고 작심 비판하고 나섰다. 3일 안 의원은 자신의... 그러면서 “환율은 1520원대를 넘보고, 유가는 100달러에 이르렀으며,코스피는 4% 이상 급락했다”면서 “국민은 피눈물을 흘리고, 기업의 시가총액 수조원이...

[6] 안철수 "코스피사이드카 때 李·與 셀카파티…위기 추경 맞나" (시사저널)
 - None

[7] 코스피2.5% 상승 5,300선 '탈환'...환율 1,505원 (YTN)
 - 어제 폭락했던코스피가 오늘은 강세로 전환해 5,300선을 회복하고 장을 마감했습니다. 원·달러 환율은 15원 가까이 내린 1,505원으로 주간 거래를 마쳤습니다. 취재기자 연결해 알아보겠습니다. 윤태인 기자, 오늘코스피는 상승 마감했죠? [기자]코스피는 5,375로 상승 출발해 한때 5,419를 넘는 등 강세를...

[8] '호르무즈 통행' 논의에코스피5,300선 회복...원-달러 환율은 10원 '뚝... (YTN)
 - None

[9] '연설 후폭풍' 털고코스피3% 상승...환율은 1,500원대로 하락 (YTN)
 - None

[10] 코스피2.5% 상승 5,300선 회복...환율 1,504원~1,511원 유지 (YTN)
 - None

[11] [속보] 5%대 빠진코스피…매도 사이드카 발동 (서울신문)
 - 46분코스피시장에 프로그램 매도호가 일시 효력정지(사이드카)가 발동했다. 앞서 오후 2시 34분에는 코스닥 시장에서 매도 사이드카가 발동된 바 있다. 장 초반 반짝 5500선을 회복했던코스피지수는 오전 10시 트럼프 대통령이 이란 전쟁 관련 대국민 연설을 시작하고부터 약세로 전환해 낙폭을...

[12] [속보]코스피·코스닥 동반 매도 사이드카…5% 급락 (노컷뉴스)
 - None

[13] [속보]코스닥 이어코스피도 '매도 사이드카' 발동 (머니투데이)
 - None

[14] [속보]코스닥 이어코스피도 매도 사이드카 발동 (아시아경제)
 - None

[15] 매도 사이드카 발동한코스피 (뉴스1)
 - None

[16] "유가 90달러냐 80달러냐"…코스피주도주, 완전히 달라진다 (파이낸셜뉴스)
 - ■전쟁 장기화에도코스피반등...증권가 촉각 4일 증권업계에 따르면코스피는 전일 2.74% 오른 5377.30에 거래를 마쳤다. 지난 2일 하루 4.47% 급락 후 반등세다. 지난 1일에는 무려 8.44% 상승한 바 있다. 코스닥지수도 전일 0.70% 오르며 1060선을 회복했다. 국내 증시는 전쟁 초기 충격 국면에서는 지정학적...

[17] 코스피, 4.47% 하락한 5234.05 마감…코스닥 5.36%↓(2보) (뉴스1)
 - 2일코스피는 전일 종가와 비교해 244.65포인트(p)(4.47%) 하락한 5234.05로 거래를 마쳤다. 코스닥은 전일 대비 59.84포인트(p)(5.36%) 하락한 1056.34로 마감했다. 오후 3시 30분 기준 서울외환시장에서 달러·원 환율은 전일 주간종가 대비 18.4원 오른 1519.7원을 기록했다.

[18] 코스피4%대 급락 5,200대 마감…코스닥도 5%↓ (KBS)
 - 도널드 트럼프 미국 대통령의 연설로 중동 사태 조기 종식에 대한 기대가 사라지면서코스피와 코스닥 모두 급락했습니다. 오늘(2일)코스피는 어제보다 244.65포인트, 4.47% 내린 5,234.05에 장을 마쳤습니다.코스피지수는 어제보다 72.99포인트, 1.33% 오른 5,551.69로 출발해 상승세를 보였지만, 장중...

[19] 코스피, 4%대 급락 5,200대 마감…코스닥도 5% 폭락 (연합뉴스)
 - None

[20] 어제는 '매수' 오늘은 '매도' 사이드카…급락장에 '롤러코스피' (주간조선)
 - 도널드 트럼프 미국 대통령의 대국민 연설 이후 국내 증시가 급락하면서 코스닥과코스피시장에서 잇따라 매도 사이드카가 발동됐다.... 이어코스피시장에서도 낙폭이 확대되며 매도 사이드카가 발동됐다. 한국거래소는 이날 오후 2시 46분 유가증권시장에 프로그램 매도호가 일시 효력정지...

[21] 트럼프 강경 발언에…코스닥 이어코스피도 매도 사이드카 발동(종합) (연합뉴스)
 - None

[22] [속보] 코스닥 이어...코스피도 매도 사이드카 (중앙일보)
 - None

[23] "호르무즈 열리나" 기관 '사자'…코스피·코스닥 동반 회복 중 (머니투데이)
 - 3일 오전 9시11분 기준코스피는 전 거래일 대비 168.76포인트(3.22%) 오른 5402.81을 나타낸다.코스피시장에서 기관이 1400억원 순매수 중이고, 개인과 외국인이 72억, 1484억원 순매도 중이다. 기관에서는 연기금 등이 938억원을 사들이고 있고, ETF(상장지수펀드) 매매 흐름을 보여주는 금융투자는 270억원을...

[24] 코스피, 호르무즈 개방 기대감에 2%대 반등…외인 '사자' 전환 (한국경제)
 - 코스피지수가 호르무즈 해협 개방 기대감에 2%대 반등에 성공했다. 외국인 투자자는 지난달 18일 이후 처음으로코스피에서 순매수로 돌아섰다. 3일코스피지수는 전일 대비 143.25포인트(2.74%) 오른 5377.3에 거래를 마감했다. 장중 5400선까지 상승하기도 했으나 미국이 이란 수도 테헤란과 인근 도시를...

[25] 코스피, 호르무즈 개방 기대감에 2%대 반등… 12거래일 만에 돌아온 외... (국민일보)
 - None

[26] "호르무즈 열리나" 기관 '사자'…코스피·코스닥 동반 회복 중 (머니투데이)
 - 3일 오전 9시11분 기준코스피는 전 거래일 대비 168.76포인트(3.22%) 오른 5402.81을 나타낸다.코스피시장에서 기관이 1400억원 순매수 중이고, 개인과 외국인이 72억, 1484억원 순매도 중이다. 기관에서는 연기금 등이 938억원을 사들이고 있고, ETF(상장지수펀드) 매매 흐름을 보여주는 금융투자는 270억원을...

[27] 코스피3% 반등...다시 5300선 회복 (조선일보)
 - 미국·이스라엘과 이란간 종전 기대감 약화로 폭락했던코스피가 호르무즈 해협 정상화 기대에 하루만에 급반등했다. 3일 한국거래소에 따르면 이날코스피는 전 거래일 대비 2.7% 오른 5375.50에 개장했다. 장 초반에는 상승폭을 키우며 5400선을 회복하기도 했다. 전날 도널드 트럼프 미국 대통령의...

[28] 트럼프 한마디 요동쳐도…"코스피5,000~5,700선, 딥밸류 구간" (한국경제TV)
 - 코스피가 지정학 리스크와 유가 불안, 트럼프 미국 대통령 발언에 따른 ‘일희일비 장세’를 이어가겠지만, 밸류에이션과 실적 모멘텀을 감안하면 중장기 매수 관점은 유효하다는 분석이 나온다. 4일 나정환 NH투자증권 연구원은 보고서에서 다음주코스피예상 밴드를 5000~5700선으로 제시했다. 그는 상승...

[29] “팔 만큼 팔았다” 돌아온 외국인…코스피반등 열쇠 될까 [코주부] (서울경제)
 - 3일코스피지수는 전장보다 2.74% 오른 5377.30에 거래를 마쳤다. 유가증권시장에서 가장 눈에 띄는 대목은 외국인의 수급 전환이다. 외국인은 지난 3월 한 달간 무려 35조 원 이상을 팔아치웠다. 3월 19일부터 4월 2일까지는 12거래일 연속코스피순매도 행진을 이어갔다. 하지만 3일에는 8145억 원을 대거...

[30] 코스피, 장 초반 3% 상승 5,300대 회복…코스닥도 올라 (연합뉴스)
 - 코스피가 3일 장 초반 3% 넘게 상승해 5,300대를 회복했다. 이날 오전 9시 2분 현재코스피는 전장보다 160.77포인트(3.07%) 오른 5,394.82다. 지수는 전장보다 141.45포인트(2.70%) 오른 5,375.50으로 출발했다. 같은 시각 코스닥지수도 전장보다 25.89포인트(2.45%) 오른 1,082.23이다.

[31] 한달 동안에만 22% 오르락내리락…비트코인보다 컸던코스피변동률 (매일경제)
 - 3월 고·저 변동률 각 22.6%·16.8%코스피고가 6180.45 저가 5042.99코스피·코스닥서 사이드카 잇단 발동 증권가에선 4월코스피4700~6300P “22.6%(3월코스피고·저 변동률) VS 16.8%(3월 비트코인 고·저 변동률).” 한국경제가 2월 말 시작한 중동전쟁발 여파로 고환율·고유가이라는 다중 파고에 직면한 가운데...

[32] 코인보다 더 흔들린코스피…전쟁 한 달 '22.6% 롤러코스터' (주간조선)
 - None

[33] “어제는 지옥, 오늘은 천당”…사이드카 12번 터진코스피, 비트코인보... (서울경제)
 - None

[34] 코스피장 초반 5,300선 회복…환율도 내림세 (KBS)
 - 코스피가 호르무즈 해협 개방 기대감 등에 장 초반 3% 가까이 올라 5,300대를 회복했습니다.코스피지수는 오늘(3일) 141.45포인트, 2.70% 오른 5,375.50으로 출발해 상승 중입니다. 한때 5,419.45까지 올라 5,400선을 회복하기도 했습니다. 전날코스피는 도널드 트럼프 미국 대통령의 백악관 연설 이후 4.47...

[35] 트럼프 연설에 하락한코스피 (뉴시스)
 - 미국 도널드 트럼프 대통령의 강경 발언으로 미국과 이란 간 종전 기대감이 꺾이며코스피와 코스닥이 하락 마감한 2일 서울 중구 하나은행 딜링룸에서 딜러들이 업무를 보고 있다.코스피는 전 거래일(5478.70)보다 244.65포인트(4.47%) 내린 5234.05에, 코스닥 지수는 전 거래일(1116.18)보다...

[36] [포토] 트럼프 강경 발언에 하락한코스피-코스닥 (한국경제)
 - None

[37] 트럼프 연설에 하락한코스피 (뉴시스)
 - None

[38] 트럼프 연설에 하락한코스피 (뉴시스)
 - None

[39] 트럼프 연설에 하락한코스피 (뉴시스)
 - None

[40] 12일 만에 돌아온 외국인…코스피5300선 회복 마감 (서울신문)
 - 원달러 환율 14.5원 내린 1505.2원호르무즈 해협이 다시 열릴 것이라는 기대감에코스피가 전날 하락 폭을 일부 되돌림했다. 기관과 외국인이 동반 순매수한 반면 개인만 내다 팔았다. 원달러 환율 역시 1500원대 초반으로 내려왔다. 3일코스피는 전 거래일 대비 145.25포인트(2.74%) 오른 5377.30에 거래를...

[41] 돌아온 외국인 매수에코스피'5300 회복'...2.74% 상승 마감 (이코노미스트)
 - 코스피가 5300선을 회복했다. 3일코스피지수는 전장보다 143.25포인트(2.74%) 상승한 5377.30에 장을 마감했다. 유가증권시장에서는 개인이 2조4199억원을 팔았지만 외국인과 기관이 각각 9492억원, 8630억원을 순매수하며 지수 상승을 이끌었다. 특히 외국인은 12거래일 만에 순매수로 돌아섰다. 아울러...

[42] 12거래일 만에 돌아온 외국인…코스피5,370선 회복 (한국경제TV)
 - 코스피가 3일 2% 넘게 상승해 5,370대를 회복했다. 이날코스피는 전 거래일 대비 143.25포인트(2.74%) 오른 5,377.30에 장을 마쳤다. 지수는 장 초반 기관 매수세에 상승폭을 넓히며 전 거래일 대비 185.40포인트(3.54%) 오른 5,419.45를 기록했다. 이후 오름폭을 소폭 줄인 채 상승세를 이어갔다. 유가증권시장에서...

[43] 돌아온 외국인에코스피'질주'…2.7% 상승 마감 (노컷뉴스)
 - 외국인 12일 만에 '사자' 삼성전자 4.37%·SK하이닉스 5.54% 급등 환율 1505.2원, 14.5원 내려 중동발 지정학적 리스크 완화 기대감과 함께 외국인이 돌아오면서코스피가 3% 가까운 반등에 성공했다. 3일코스피지수는 전 거래일보다 2.74% 오른 5377.30으로 거래를 마쳤다. 전날코스피는 도널드 트럼프 미국...

[44] 코스피-코스닥 상승 출발 (뉴시스)
 - 코스피가 전 거래일(5478.70)보다 72.99포인트(1.33%) 상승한 5551.69에 개장한 2일 오전 서울 중구 하나은행 딜링룸 전광판에 지수가 표시되고 있다. 코스닥 지수는 전 거래일(1116.18)보다 13.98포인트(1.25%) 오른 1130.16, 서울 외환시장에서 원·달러 환율은 전 거래일 주간거래 종가(1501....

[45] 코스피-코스닥 상승 출발 (뉴시스)
 - None

[46] 상승 출발한코스피-코스닥 (뉴시스)
 - None

[47] 호르무즈 기대감에코스피, 장초반 5300선 회복…환율 1510원 (국민일보)
 - 코스피가 3일 개장 직후 3% 이상 급등하며 단숨에 5300선을 단숨에 회복했다. 이날 오전 9시24분 기준코스피지수는 전 거래일 대비 143.20포인트(2.74%) 뛰어오른 5377.25를 기록 중이다. 전날코스피는 도널드 트럼프 미국 대통령의 조기 종전 기대를 꺾는 연설 여파로 4.47%나 하락며 5230대까지...

[48] 급락한코스피 (뉴스1)
 - 코스피·코스닥 지수가 급락하면서 매도 사이드카(프로그램 매도호가 일시 효력 정지)가 발동된 2일 오후 서울 중구 하나은행 딜링룸에 종가가 나오고 있다. 이날코스피는 전 거래일(5478.70)보다 244.65포인트(4.47%) 내린 5234.05, 코스닥 지수는 전 거래일(1116.18)보다 59.84포인트(5.36...

[49] 급락한코스피·코스닥 (뉴스1)
 - None

[50] 하루 만에 급락한코스피 (뉴스1)
 - None

In [7]:
print_get_news_data(keyword="코스닥")

[1] 트럼프 강경 발언에…코스닥이어 코스피도 매도 사이드카 발동(종합) (연합뉴스)
 - 황철환 이민영 기자 = 이란 사태 조기종식 기대에 찬물을 끼얹은 도널드 트럼프 미국 대통령의 대국민 연설 이후 증시가 급락하면서 2일코스닥... 이에 앞서 오후 2시 34분 32초께에는코스닥150선물가격 및 현물지수의 변동으로코스닥시장에서도 매도 사이드카가 발동, 5분간 프로그램매도호가의...

[2] [속보]코스닥이어...코스피도 매도 사이드카 (중앙일보)
 - None

[3] 코스닥이어 코스피도 매도 사이드카 발동 (국민일보)
 - None

[4] [속보]코스닥이어 코스피도 매도 사이드카 발동 (매일경제)
 - None

[5] 트럼프 강경 발언에…코스닥이어 코스피도 '매도 사이드카' 발동 (뉴시스)
 - None

[6] BNK자산운용, BNK코스닥벤처펀드 출시 (뉴시스)
 - BNK자산운용은 벤처기업과코스닥상장(예정) 기업에 투자하는 'BNK코스닥벤처펀드'를 출시한다고 3일 밝혔다. BNK코스닥벤처펀드는 벤처기업 신주에 15% 이상, 벤처기업 또는 벤처기업 해제 후 7년 이내코스닥상장 중소·중견기업의 신주 및 구주에 35% 이상 투자하는 상품이다. 해당 투자 요건을 충족할...

[7] BNK자산운용,코스닥·벤처 투자 흐름에 맞춘 전략형 펀드 출시 (데일리한국)
 - None

[8] [게시판] BNK자산운용, 'BNK코스닥벤처펀드' 출시 (연합뉴스)
 - None

[9] 코스피, 외국인 매수에 5,370대 회복…코스닥도 올라 (부산일보)
 - 코스닥지수도 전장보다 7.41포인트(0.70%) 오른 1,063.75에 마감했다. 지수는 전장보다 22.83포인트(2.16%) 오른 1,079.17로 출발해 상승폭을 줄여 잠시 하락 전환하기도 했으나 다시 상승세로 돌아섰다. 알테오젠(3.84%)이 상승해 에코프로를 제치고코스닥시가총액 1위로 올라섰다. 삼천당제약(6.40%)도...

[10] 코스피, 외국인 복귀에 2.7% 상승 5,370대 마감…코스닥도 올라(종합) (연합뉴스)
 - None

[11] 코스피, 4.47% 하락한 5234.05 마감…코스닥5.36%↓(2보) (뉴스1)
 - 2일 코스피는 전일 종가와 비교해 244.65포인트(p)(4.47%) 하락한 5234.05로 거래를 마쳤다.코스닥은 전일 대비 59.84포인트(p)(5.36%) 하락한 1056.34로 마감했다. 오후 3시 30분 기준 서울외환시장에서 달러·원 환율은 전일 주간종가 대비 18.4원 오른 1519.7원을 기록했다.

[12] 급락장에코스닥매도 사이드카 발동…한 달 만 (SBS)
 - 있다코스닥지수가 급락하면서 오늘(2일) 프로그램매도호가 일시효력정지(사이드카)가 약 한 달 만에 발동했습니다. 한국거래소에 따르면 오늘 낮 2시 34분 32초쯤코스닥150선물가격 및 현물지수의 변동으로 5분간 프로그램매도호가의 효력이 정지됐습니다. 발동 시점 당시코스닥150선물가격은...

[13] [속보]코스닥급락…'매도 사이드카' 한 달 만에 발동 (한국경제)
 - None

[14] 코스닥, 6%대 급락에 매도사이드카 발동 (지디넷코리아)
 - None

[15] 급락장에코스닥매도 사이드카 발동…한 달만 (연합뉴스)
 - None

[16] ‘트럼프 후폭풍’ 코스피 4.47% 내린 5200선…코스닥도 급락 (아시아경제)
 - None

[17] 벤처업계 "코스닥승강제, 해외 상장·상장 포기로 이어질 수도" (아시아경제)
 - 벤처업계가 정부의 '코스닥승강형 세그먼트 도입 방향'에 대해 정교한 설계가 필요하다고 강조했다. 3일 혁신벤처단체협의회(벤처기업협회·이노폴리스벤처협회·초기투자액셀러레이터협회 등)는 공식 입장문을 통해 "'코스닥승강형 세그먼트 도입 방향'에 대해 벤처·스타트업 업계 전반의 우려가 적지 않다"며...

[18] "코스닥1·2부 도입, 시장 왜곡·낙인효과 우려" (파이낸셜뉴스)
 - None

[19] 혁단협,코스닥1·2부 리그 개편 우려…"시장 왜곡·낙인 효과 초래" (머니투데이)
 - None

[20] 벤처업계 “코스닥승강제 도입 다시 검토해야” (서울경제)
 - None

[21] 벤처업계 ‘코스닥1·2부제’ 우려…“테슬라도코스닥왔으면 2부 편입... (매일경제)
 - None

[22] [속보]코스닥이어 코스피도 매도 사이드카 발동 (국제신문)
 - 코스닥이어 코스피도 매도 사이드카 발동

[23] [속보]코스닥이어 코스피도 매도 사이드카 발동 (아시아경제)
 - None

[24] 코스피·코스닥급락에 매도 사이드카 발동 (뉴스1)
 - None

[25] [속보]코스닥이어 코스피도 매도 사이드카 발동 (연합뉴스)
 - None

[26] [속보]코스닥이어 코스피도 매도 사이드카 발동 (MBN)
 - None

[27] 코스닥급등에 매수 사이드카 발동…약 한 달 만 (KBS)
 - 코스닥지수가 급등하면서 프로그램 매수호가 일시 효력 정지(사이드카)가 약 한 달 만에 발동했습니다. 한국거래소에 따르면 오늘(1일) 오후 2시 8분 51초쯤코스닥150선물가격과코스닥150지수의 변동으로 5분간 프로그램 매수호가의 효력이 정지됐습니다. 발동 시점 당시코스닥150선물은 전일...

[28] 코스닥급등에 매수 사이드카 발동…약 한 달만 (연합뉴스)
 - None

[29] [속보] 코스피 이어코스닥도 매수 사이드카 발동 (매일경제)
 - None

[30] 코스닥상장사, 지난해 영업익 17% 증가…10곳 중 6곳 흑자 (조선비즈)
 - 코스닥시장 12월 결산법인 2025 사업연도 결산실적 지난해코스닥상장 기업들의 실적이 전반적으로 개선된 것으로 나타났다.코스닥기업 10곳 중 약 6곳이 흑자를 기록하며 비교적 양호한 성적을 거뒀다. 3일 한국거래소가 발표한 ‘코스닥시장 12월 결산법인 2025 사업연도 결산 실적’에...

[31] 코스닥상장사, 지난해 영업익 17%↑…9곳 중 5곳 흑자[2025년 실적결산... (뉴시스)
 - None

[32] 5400 안팎에서 2%대 강세 유지하는 코스피…코스닥반짝 약세 후 회복 (머니투데이)
 - 코스닥은 외국인과 기관 동반 동반 매도로 오전 한때 약세였으나, 개인의 매수세에 강세를 회복했다. 3일 오후 1시51분 기준 코스피는 전 거래일... 같은 시각코스닥은 전 거래일 대비 4.64포인트(0.44%) 오른 1060.98에 거래되고 있다.코스닥은 이날 전 거래일 대비 22.83포인트(2.16%) 오른 1079.17로 거래를...

[33] 5400 안팎에서 2%대 강세 유지하는 코스피…코스닥반짝 약세 후 회복 (머니투데이)
 - 코스닥은 외국인과 기관 동반 동반 매도로 오전 한때 약세였으나, 개인의 매수세에 강세를 회복했다. 3일 오후 1시51분 기준 코스피는 전 거래일... 같은 시각코스닥은 전 거래일 대비 4.64포인트(0.44%) 오른 1060.98에 거래되고 있다.코스닥은 이날 전 거래일 대비 22.83포인트(2.16%) 오른 1079.17로 거래를...

[34] "호르무즈 열리나" 기관 '사자'…코스피·코스닥동반 회복 중 (머니투데이)
 - None

[35] 트럼프 연설에 하락한 코스피-코스닥 (뉴시스)
 - 미국 도널드 트럼프 대통령의 강경 발언으로 미국과 이란 간 종전 기대감이 꺾이며 코스피와코스닥이 하락 마감한 2일 서울 중구 하나은행 딜링룸에서 딜러들이 업무를 보고 있다. 코스피는 전 거래일(5478.70)보다 244.65포인트(4.47%) 내린 5234.05에,코스닥지수는 전 거래일(1116.18)보다...

[36] [포토] 트럼프 강경 발언에 하락한 코스피-코스닥 (한국경제)
 - None

[37] [포토]코스피, 4.47% 하락한 5234.05 마감…코스닥5.36% (이데일리)
 - None

[38] 트럼프 연설에 하락한 코스피-코스닥 (뉴시스)
 - None

[39] 트럼프 연설에 하락한 코스피-코스닥 (뉴시스)
 - None

[40] 급락한 코스피·코스닥 (뉴스1)
 - 코스피·코스닥지수가 급락하면서 매도 사이드카(프로그램 매도호가 일시 효력 정지)가 발동된 2일 오후 서울 중구 하나은행 딜링룸에 코스피,코스닥종가가 나오고 있다. 이날 코스피는 전 거래일(5478.70)보다 244.65포인트(4.47%) 내린 5234.05,코스닥지수는 전 거래일(1116.18)보다 59....

[41] 급락한 코스피·코스닥 (뉴스1)
 - None

[42] 코스피·코스닥급락, 환율 상승 (뉴스1)
 - None

[43] "코스닥ETF에 삼성전자 담아도 된다" [수상한액티브③] (한국경제TV)
 - 나스닥 액티브 ETF가 뉴욕증권거래소(NYSE) 종목을 대거 편입하거나, 코스피 액티브 ETF가코스닥종목을 담는 등 시장의 경계를 넘나드는 식이다.... ▲ 거래소 "코스닥액티브ETF에는 코스피 종목도 편입 가능" 심지어 최근 상장한코스닥액티브 ETF에 삼성전자 등을 담아도 되는지에 대해서도 거래소는...

[44] [속보]코스피, 2.74% 오른 5377.30...코스닥, 0.70% 상승 마감 (이데일리)
 - [속보]코스피, 2.74% 오른 5377.30...코스닥, 0.70% 상승 마감

[45] 코스닥5% 급락할 때 112% 올랐다…‘입성 성공’ 인벤테라, IPO 열기 이... (매일경제)
 - ‘나노의약품 개발’ 인벤테라코스닥상장 첫날 ‘따블’ 마감 “상장 초기에는 변동성 높아 적정 가치구간 확인해 접근을”코스닥새내기주 인벤테라가 상장 첫날 증시 급락장 속에서도 공모가 대비 2배 이상 상승하며 흥행에 성공했다. 최근코스닥중소형주 중심으로 이어지고 있는 공모주 열기를...

[46] [특징주] 인벤테라,코스닥입성 첫날 장 초반 150%↑ (연합뉴스)
 - None

[47] [특징주] 인벤테라,코스닥입성 첫날 '따블' 마감(종합) (연합뉴스)
 - None

[48] 코스피, 2.7% 상승 5,370대 회복…코스닥도 올라 (연합뉴스)
 - 3일 서울 중구 하나은행 본점 딜링룸 현황판에 코스피,코스닥지수가 표시돼 있다. 이날 코스피는 전 거래일 대비 143.25p(2.74%) 오른 5,377.30으로,코스닥지수는 전장보다 7.41p(0.70%) 오른 1,063.75로 마감했다. 2026.4.3

[49] 코스피, 2.7% 상승 5,370대 회복…코스닥도 올라 (연합뉴스)
 - None

[50] 코스피, 2.7% 상승 5,370대 회복…코스닥도 올라 (연합뉴스)
 - None

In [ ]:
# 수집한 데이터를 pandas를 통해 데이터프레임으로 전환
import pandas as pd

kospi_list = get_news_data(keyword="코스피")
kosdaq_list = get_news_data(keyword="코스닥")

df_kospi = pd.DataFrame(kospi_list)
df_kospi["keyword"] = "코스피"

df_kosdaq = pd.DataFrame(kosdaq_list)
df_kosdaq["keyword"] = "코스닥"

In [9]:
df_kospi.head(10)

,title,press,summary,keyword
0,"코스피, 외국인 복귀에 2.7% 상승 5,370대 마감…코스닥도 올라(종합)",연합뉴스,"환율 급락 속 외국인 12일만에 '사자'…삼성전자·하이닉스 급등 알테오젠, 에코프로...",코스피
1,"코스피, 외국인 매수에 5,370대 회복…코스닥도 올라",부산일보,NaN,코스피
2,"외국인, 12일 만에 귀환…코스피, 2%대 상승 마감(종합)",뉴시스,미국 도널드 트럼프 대통령의 이란 전쟁 관련 강경 발언의 여파로 급락했던코스피가 호...,코스피
3,"외국인의 귀환…코스피, 2%대 상승 마감",채널A,NaN,코스피
4,안철수 “코스피비명지르는데 대통령·여당은 셀카 파티…전쟁 위기 맞...,문화일보,"의원이 “코스피사이드카 터질 때, 이 대통령과 민주당은 국회에서 환호, 박수, 셀카...",코스피
5,"안철수 ""코스피사이드카 때 李·與 셀카파티…위기 추경 맞나""",시사저널,NaN,코스피
6,"코스피2.5% 상승 5,300선 '탈환'...환율 1,505원",YTN,"어제 폭락했던코스피가 오늘은 강세로 전환해 5,300선을 회복하고 장을 마감했습니다...",코스피
7,"'호르무즈 통행' 논의에코스피5,300선 회복...원-달러 환율은 10원 '뚝...",YTN,NaN,코스피
8,"'연설 후폭풍' 털고코스피3% 상승...환율은 1,500원대로 하락",YTN,NaN,코스피
9,"코스피2.5% 상승 5,300선 회복...환율 1,504원~1,511원 유지",YTN,NaN,코스피

In [ ]:
# 두 키워드 데이터프레임을 행방향 결합
df_total = pd.concat([df_kospi, df_kosdaq], ignore_index=True)

print(f"전체 수집 건수: {len(df_total)}")
display(df_total.head())

전체 수집 건수: 100

,title,press,summary,keyword
0,"코스피, 외국인 복귀에 2.7% 상승 5,370대 마감…코스닥도 올라(종합)",연합뉴스,"환율 급락 속 외국인 12일만에 '사자'…삼성전자·하이닉스 급등 알테오젠, 에코프로...",코스피
1,"코스피, 외국인 매수에 5,370대 회복…코스닥도 올라",부산일보,NaN,코스피
2,"외국인, 12일 만에 귀환…코스피, 2%대 상승 마감(종합)",뉴시스,미국 도널드 트럼프 대통령의 이란 전쟁 관련 강경 발언의 여파로 급락했던코스피가 호...,코스피
3,"외국인의 귀환…코스피, 2%대 상승 마감",채널A,NaN,코스피
4,안철수 “코스피비명지르는데 대통령·여당은 셀카 파티…전쟁 위기 맞...,문화일보,"의원이 “코스피사이드카 터질 때, 이 대통령과 민주당은 국회에서 환호, 박수, 셀카...",코스피

In [11]:
print("--- 결측치 탐지 현황 ---")
print(df_total.isnull().sum())

--- 결측치 탐지 현황 ---
title       0
press       0
summary    57
keyword     0
dtype: int64

## 📊 결측치 탐지 및 처리 프로세스

---

### 1. 결측치 유형의 이론적 배경

- MCAR(완전 무작위 결측): 데이터의 누락이 다른 변수나 데이터 자체와 아무런 상관관계 없이 발생한 경우.
- MAR(무작위 결측): 결측 여부가 관측된 다른 변수(X)에 의해 설명될 수 있는 경우.
- MNAR(비무작위 결측): 결측 원인이 누락된 값(Y)자체에 있거나 데이터셋 외부 요인에 의한 경우.
    > 참고: 7강 '결측치 탐지'

---

### 2. 수집한 데이터의 분석 및 유형 판정

> **[판정 결과] MAR(Missing At Random)**

- 관측 데이터와의 연관성: 수집된 데이터프레임 내 `title(제목)`과 `press(언론사)` 변수는 모두 정상적으로 관측되었습니다.
- 추론: `summary(요약)`에 결측이 발생한 행들을 분석한 결과, 주로 메인 기사에 부속되어 제목에 특정 기호(... 등)가 포함된 '하위 관련 뉴스' 형태임을 확인했습니다.
- 판정 근거: 즉, 제목의 형태라는 기 관측된 정보(X)를 통해 요약문(Y)의 부재를 예측할 수 있으므로, 본 결측치는 MAR 메커니즘을 따르는 것으로 판단됩니다.

---

### 3. 데이터 정제 전략

본 과제의 목적은 키워드별 뉴스 요약문의 텍스트 분석입니다.

### 처리 방법: 완전 제거(Listwise Deletion)

| 분석 항목                 | 상세 내용                                                                                                                                                |
| :------------------------ | :------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 결측치 비율에 대한 고찰   | 수집한 100개의 데이터 중 결측 비율이 57%(과제 작성 당시)로 매우 높으나, 본 데이터는 수치형이 아닌 비정형 텍스트(Text)라는 특수성이 있음.                 |
| 대치 기법 적용의 불가능성 | 요약문(`summary`)은 텍스트 데이터로, 평균/중앙값/KNN 대치가 불가능하며, 임의의 상수로 채울 경우 **단어 빈도 분석 결과에 심각한 편향**을 초래함.          |
| 도메인 지식을 활용        | 결측 행은 메인 뉴스를 짧게 반복하거나 제목만 노출되는 '하위 뉴스 리스트'로 판단됨. 이를 제거하는 것이 정보의 손실 보다 데이터 중복 정제 측면에서 유리함. |

> **[결론]**
> 결측 비율이 높음에도 불구하고, 분석 데이터의 품질과 텍스트 분석의 특수성을 고려하여 결측치가 포함된 행을 모두 제거하는 **완전 제거** 방법을 최종 채택하였습니다.
>
> _향후 과제 수행 시, 최종 분석 대상(30건)의 2~3배수를 초기 수집 목표로 설정하여 데이터 가용성을 확보할 필요가 있음을 시사함._

In [ ]:
# dropna를 통한 결측치 행 완전 제거
df_clean = df_total.dropna(subset=["summary"])

print(f"제거 전 데이터 수: {len(df_total)}")
print(f"제거 후 데이터 수: {len(df_clean)}")

제거 전 데이터 수: 100
제거 후 데이터 수: 43